### ISSUE TITLE
rebar3 plugin

### ISSUE THREAD

**Issue by dzimi** [parapluu/nifty#51]
Hi !
I admit that I’ve never created any NIF, but if I do I will definitely use niffty. I think it would be great if niffty would be available as rebar3 plugin. This will allow to use it the same as erlyDTL, neotoma, diameter and other useful libraries.  
Regards.

**Comment by kostis** [comment]
I do not see any issue here; I see only a wish.  Moreover, this wish is not substantiated by any use case that shows why having nifty as a rebar3 plugin is something which is needed.  I am closing this issue.  Feel free to reopen a new one when you have a concrete case where having nifty as a rebar3 (or whatever else) plugin is something needed/nice to have.  Also, please supply us this case so that we know whether the plugin we create is the right/appropriate one or not.
